apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: InternRFC-app-work-user
  template:
    metadata:
      labels:
        app: InternRFC-app-work-user
    spec:
      containers:
      - name: Work-User-container
        image: 533267283761.dkr.ecr.eu-central-1.amazonaws.com/workrapport-user:latest
        ports:
        - containerPort: 3000
